.github/workflows/build-test-publish.yml
build.gradle.kts

Only publish our generated JAR when on the main branch.
Solves PZ-766

feat: only publish on main branch

---

build.gradle.kts

Use custom INFONL version to make it very clear that it is our custom INFO version that we are using.
Solves PZ-792

chore: use custom INFONL version

---

.github/workflows/codeql-analysis.yml
build.gradle.kts

Add CodeQL code analysis
Solves PZ-836

feat: add CodeQL analysis

---

.github/workflows/check-for-conventional-commits.yml
CONTRIBUTING.md

Added conventional commits check GitHub workflow. Added contributing docs.
Solves PZ-1009

chore: use conventional commits

---

.github/workflows/build-test-publish.yml
build.gradle.kts

Added automatic Git tag and releasing.
Solves PZ-1008

feat: automatic tag and release

---

INSTALL.md

added documentation about the release process #major
tests the release process

chore: added documentation about the release process #major

---

.github/workflows/build-test-publish.yml
INSTALL.md

Added GitHub plugin to automatically create a GitHub release from a tag.
Solves PZ-1037

feat: create GitHub release

---

.github/workflows/update-gradle-wrapper.yml

Added GitHub workflow to automatically update the Gradle wrapper.
Solves PZ-1039

feat: automatically update the Gradle wrapper

---

.github/workflows/build-test-publish.yml
src/main/java/net/sf/webdav/WebdavStatus.java
src/test/java/net/sf/webdav/methods/DoCopyTest.java
src/test/java/net/sf/webdav/methods/DoDeleteTest.java
src/test/java/net/sf/webdav/methods/DoGetTest.java
src/test/java/net/sf/webdav/methods/DoHeadTest.java
src/test/java/net/sf/webdav/methods/DoLockTest.java
src/test/java/net/sf/webdav/methods/DoMkcolTest.java
src/test/java/net/sf/webdav/methods/DoMoveTest.java
src/test/java/net/sf/webdav/methods/DoNotImplementedTest.java
src/test/java/net/sf/webdav/methods/DoOptionsTest.java
src/test/java/net/sf/webdav/methods/DoPropfindTest.java
src/test/java/net/sf/webdav/methods/DoProppatchTest.java
src/test/java/net/sf/webdav/methods/DoPutTest.java
src/test/java/net/sf/webdav/methods/DoUnlockTest.java
src/test/java/net/sf/webdav/methods/TestingOutputStream.java
src/test/java/net/sf/webdav/testutil/MockTest.java

Fixed most unit tests (all were failing). Disabled a few other tests to look at later.
Solves PZ-1052

feat: fixed most unit tests

---

README.md

Add GitHub CI build code repository badge.
Solves PZ-1062

chore: add GitHub CI build code repository badge

---

.github/workflows/build-test-publish.yml
INSTALL.md

Automatically close and release the Sonatype Nexus staging repo after publishing.
Solves PZ-1061

feat: automatically close and release the Sonatype Nexus staging repo

---

README.md

Added GitHub license badge.
Solves PZ-1064

feat: add GitHub license badge

---

.github/workflows/build-test-publish.yml
README.md
build.gradle.kts

Added Codecov code coverage status badge. Powered by the Jacoco code coverage plugin.
Solves PZ-1063

feat: add codecov GitHub badge

---

.github/workflows/trivy-code-scanning.yml

Added Trivy codebase scanning workflow.
Solves PZ-1184

feat: add Trivy codebase scanning workflow

---

src/main/java/nl/info/webdav/IMethodExecutor.java
src/main/java/nl/info/webdav/IMimeTyper.java
src/main/java/nl/info/webdav/IWebdavStore.java
src/main/java/nl/info/webdav/LocalFileSystemStore.java
src/main/java/nl/info/webdav/StoredObject.java
src/main/java/nl/info/webdav/WebDavServletBean.java
src/main/java/nl/info/webdav/WebdavServlet.java
src/main/java/nl/info/webdav/WebdavStatus.java
src/main/java/nl/info/webdav/fromcatalina/MD5Encoder.java
src/main/java/nl/info/webdav/fromcatalina/RequestUtil.java
src/main/java/nl/info/webdav/fromcatalina/URLEncoder.java
src/main/java/nl/info/webdav/fromcatalina/XMLHelper.java
src/main/java/nl/info/webdav/fromcatalina/XMLWriter.java
src/main/java/nl/info/webdav/locking/LockedObject.java
src/main/java/nl/info/webdav/locking/ResourceLocks.java
src/main/java/nl/info/webdav/methods/AbstractMethod.java
src/main/java/nl/info/webdav/methods/DoCopy.java
src/main/java/nl/info/webdav/methods/DoDelete.java
src/main/java/nl/info/webdav/methods/DoGet.java
src/main/java/nl/info/webdav/methods/DoHead.java
src/main/java/nl/info/webdav/methods/DoLock.java
src/main/java/nl/info/webdav/methods/DoMkcol.java
src/main/java/nl/info/webdav/methods/DoMove.java
src/main/java/nl/info/webdav/methods/DoNotImplemented.java
src/main/java/nl/info/webdav/methods/DoOptions.java
src/main/java/nl/info/webdav/methods/DoPropfind.java
src/main/java/nl/info/webdav/methods/DoProppatch.java
src/main/java/nl/info/webdav/methods/DoPut.java
src/main/java/nl/info/webdav/methods/DoUnlock.java

Clean up Java code a bit.
Solves PZ-1235

chore: clean up code

---

src/main/java/nl/info/webdav/methods/DoPut.java
src/test/java/nl/info/webdav/methods/DoMoveTest.java
src/test/java/nl/info/webdav/methods/DoPutTest.java
src/test/java/nl/info/webdav/methods/DoUnlockTest.java
src/test/java/nl/info/webdav/testutil/MockTest.java

Fixed one failing unit test.
Solves PZ-1054

chore: fix failing unit test

---

.github/workflows/snyk-code-scanning.yml

Added Snyk code and Gradle scanning
Solves PZ-1282

feat: add Snyk Gradle dependency scanning

---

.github/workflows/build-test-publish.yml

Enabled auto-merge of Dependabot PRs for minor ugprades.
Solves PZ-1418

feat: enable Dependabot auto merge of minor upgrades

---

.github/workflows/build-test-publish.yml
.github/workflows/codeql-analysis.yml
INSTALL.md
build.gradle.kts
src/main/java/nl/info/webdav/methods/AbstractMethod.java

Upgraded to Java 21.
Solves PZ-1483

chore: upgraded from Java 17 to 21

---

.github/CODEOWNERS

Thanks for the work Rick & Jorann!
Solves PZ-1885

chore: updated codeowners file for new team members

---

build.gradle.kts
gradle/libs.versions.toml

Fixed issues in the Gradle build file. Also upgraded Java code compatibility to JDK 21.
Solves PZ-2587

fix: fixed issues in the Gradle build file

---

.github/workflows/build-test-publish.yml
.github/workflows/codeql-analysis.yml
src/main/java/nl/info/webdav/WebDavServletBean.java
src/main/java/nl/info/webdav/methods/DoCopy.java

Fixed exceptions when using webdavservlet to open word document. Also upgraded deprecated Gradle actions.
Solves PZ-2588

fix: fix exceptions when using webdavservlet to open word document

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Added code of conduct. See: https://opensource.guide/code-of-conduct/
Solves PZ-3273

chore: added code of conduct

---

renovate.json

Add initial renovate config based on best-practices
didn't disable dependabot yet

feat: Update renovate.json

---

.github/workflows/build-test-publish.yml
.github/workflows/trivy-code-scanning.yml

Remove leftover Dependabot configuration.
Solves PZ-5870

chore: remove leftover Dependabot configuration

---

build.gradle.kts

Updated the list of developers in the generated pom.xml.
Solves PZ-7806

chore: updated the list of developers in the generated pom.xml
